const STORAGE_KEY="construction-board-v1";
const BOARD_FIELDS=[
{key:"workType",labelKey:"labelWorkType",showKey:"showWorkType",defaultLabel:"工種",type:"text"},
{key:"location",labelKey:"labelLocation",showKey:"showLocation",defaultLabel:"場所",type:"text"},
{key:"workDate",labelKey:"labelWorkDate",showKey:"showWorkDate",defaultLabel:"施工日",type:"date"},
{key:"worker",labelKey:"labelWorker",showKey:"showWorker",defaultLabel:"施工者",type:"text"},
{key:"workContent",labelKey:"labelWorkContent",showKey:"showWorkContent",defaultLabel:"作業内容",type:"multiline"},
{key:"note",labelKey:"labelNote",showKey:"showNote",defaultLabel:"備考",type:"text"},
];
const defaultBoard={projectName:"〇〇道路改良工事",workType:"施工状況",location:"現場内",workDate:new Date().toISOString().slice(0,10),worker:"",workContent:"",note:"",photoNumber:"1",albumCategory:"施工状況",labelWorkType:"工種",labelLocation:"場所",labelWorkDate:"施工日",labelWorker:"施工者",labelWorkContent:"作業内容",labelNote:"備考",showWorkType:true,showLocation:true,showWorkDate:true,showWorker:true,showWorkContent:true,showNote:true};
const state={board:{...defaultBoard},history:[],projects:["〇〇道路改良工事"],selectedPanel:"inputPanel",boardSize:"compact",photo:null,photoName:"",composedUrl:""};
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const els={syncStatus:$("#syncStatus"),projectSelect:$("#projectSelect"),saveProjectButton:$("#saveProjectButton"),boardForm:$("#boardForm"),blackboardPreview:$("#blackboardPreview"),photoInput:$("#photoInput"),photoName:$("#photoName"),boardPosition:$("#boardPosition"),boardScale:$("#boardScale"),composeCanvas:$("#composeCanvas"),downloadLink:$("#downloadLink"),historyList:$("#historyList")};
function normalizeWorkContent(v){return String(v??"").replaceAll("\r\n","\n").replaceAll("\r","\n").split("\n").slice(0,4).join("\n")}
function normalizeBoard(board){const n={...defaultBoard,...board};delete n.station;if(!n.workContent)n.workContent=[1,2,3,4].map(i=>n[`workContent${i}`]).filter(Boolean).join("\n");n.workContent=normalizeWorkContent(n.workContent);if(!n.labelWorkContent)n.labelWorkContent=n.labelWorkContent1||n.labelWorkContent2||n.labelWorkContent3||n.labelWorkContent4||"作業内容";if(n.showWorkContent===undefined)n.showWorkContent=[1,2,3,4].some(i=>n[`showWorkContent${i}`]!==false);[1,2,3,4].forEach(i=>{delete n[`workContent${i}`];delete n[`labelWorkContent${i}`];delete n[`showWorkContent${i}`]});BOARD_FIELDS.forEach(f=>{n[f.labelKey]=n[f.labelKey]||f.defaultLabel;n[f.showKey]=n[f.showKey]!==false&&n[f.showKey]!=="false"});return n}
function loadState(){const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return;try{const saved=JSON.parse(raw);Object.assign(state,{...saved,board:normalizeBoard({...defaultBoard,...saved.board}),photo:null,composedUrl:""})}catch{localStorage.removeItem(STORAGE_KEY)}}
function persistState(){localStorage.setItem(STORAGE_KEY,JSON.stringify({board:state.board,history:state.history,projects:state.projects,selectedPanel:state.selectedPanel,boardSize:state.boardSize}));els.syncStatus.textContent=`端末内に保存済み ${new Date().toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"})}`}
function readForm(){const values=Object.fromEntries(new FormData(els.boardForm).entries());BOARD_FIELDS.forEach(f=>{values[f.showKey]=Boolean(els.boardForm.elements.namedItem(f.showKey)?.checked)});state.board=normalizeBoard({...state.board,...values})}
function fillForm(){Object.entries(state.board).forEach(([k,v])=>{const f=els.boardForm.elements.namedItem(k);if(!f)return;if(f.type==="checkbox")f.checked=Boolean(v);else f.value=v??""})}
function enforceWorkContentLimit(){const f=els.boardForm.elements.namedItem("workContent");if(!f)return;const v=normalizeWorkContent(f.value);if(f.value!==v)f.value=v}
function setActivePanel(id){state.selectedPanel=id;$$('.panel').forEach(p=>p.classList.toggle('active',p.id===id));$$('.step-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.panel===id));persistState()}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function renderProjectSelect(){const opts=[...new Set([state.board.projectName,...state.projects].filter(Boolean))];state.projects=opts;els.projectSelect.innerHTML=opts.map(p=>`<option value="${esc(p)}">${esc(p)}</option>`).join("");els.projectSelect.value=state.board.projectName}
function formatDate(date){if(!date)return"";const d=new Date(`${date}T00:00:00`);return Number.isNaN(d.getTime())?date:d.toLocaleDateString("ja-JP",{year:"numeric",month:"2-digit",day:"2-digit"})}
function getBoardRows(board){return BOARD_FIELDS.filter(f=>board[f.showKey]).map(f=>[board[f.labelKey]||f.defaultLabel,f.type==="date"?formatDate(board[f.key]):board[f.key]])}
function renderBlackboard(){const rows=getBoardRows(state.board);els.blackboardPreview.classList.toggle("large",state.boardSize==="large");els.blackboardPreview.innerHTML=`<div class="board-title"><span>${esc(state.board.projectName||"工事件名")}</span><span class="board-no">No.${esc(state.board.photoNumber||"-")}</span></div><div class="board-table">${rows.map(([l,v])=>`<div class="board-cell board-label">${esc(l)}</div><div class="board-cell board-value">${esc(v||"-")}</div>`).join("")}</div>`}
function renderHistory(){if(!state.history.length){els.historyList.innerHTML=`<li class="history-item"><div><h3>まだ履歴がありません</h3><p>保存すると写真帳用データとしてここに残ります。</p></div></li>`;return}els.historyList.innerHTML=state.history.map(r=>`<li class="history-item"><div><h3>No.${esc(r.photoNumber||"-")} ${esc(r.workType||"工種未入力")}</h3><p>${esc(r.projectName||"")}</p><p>${esc(r.albumCategory||"施工状況")} / ${esc(formatDate(r.workDate))} / ${esc(r.location||"-")}</p></div><button type="button" data-copy-record="${r.id}">再利用</button></li>`).join("")}
function renderAll(){renderProjectSelect();renderBlackboard();renderHistory();if(!els.downloadLink.href)els.downloadLink.setAttribute("aria-disabled","true")}
function makeBoardRecord(extra={}){return{id:crypto.randomUUID(),createdAt:new Date().toISOString(),...state.board,...extra}}
function saveCurrentBoard(extra={}){readForm();const record=makeBoardRecord(extra);state.history=[record,...state.history].slice(0,80);if(state.board.projectName&&!state.projects.includes(state.board.projectName))state.projects.unshift(state.board.projectName);persistState();renderAll();return record}
function duplicateWithNextNumber(){const next=parseInt(state.board.photoNumber||"0",10)+1;state.board={...state.board,photoNumber:Number.isFinite(next)?String(next):state.board.photoNumber};fillForm();renderAll();persistState()}
function copyFromRecord(record){const{id,createdAt,composedImageName,...board}=record;state.board=normalizeBoard({...defaultBoard,...board});fillForm();renderAll();setActivePanel("inputPanel")}
function drawText(ctx,text,x,centerY,maxWidth,maxHeight){const lines=[];String(text||"-").split("\n").forEach(src=>{const words=src.split(/(\s+)/).filter(Boolean);let cur="";for(const word of words.length?words:[src]){const next=cur+word;if(ctx.measureText(next).width>maxWidth&&cur){lines.push(cur.trim());cur=word.trimStart()}else cur=next}lines.push(cur.trim()||" ")});const lh=Math.min(maxHeight/Math.max(1,lines.length),parseInt(ctx.font,10)*1.18);const top=centerY-lh*lines.length/2+lh/2;lines.slice(0,4).forEach((line,i)=>{let s=line;while(ctx.measureText(s).width>maxWidth&&s.length>1)s=s.slice(0,-2)+"…";ctx.fillText(s,x,top+lh*i)})}
function drawBoardOnCanvas(ctx,x,y,width,board){const rows=getBoardRows(board),height=Math.round(width*.72),labelWidth=Math.round(width*.28),titleHeight=Math.round(height*.18),weights=rows.map(([,v])=>Math.min(4,Math.max(1,String(v||"-").split("\n").length))),total=weights.reduce((s,w)=>s+w,0)||1,bodyHeight=height-titleHeight;ctx.save();ctx.fillStyle="#143d2c";ctx.fillRect(x,y,width,height);ctx.strokeStyle="#6a4f2b";ctx.lineWidth=Math.max(2,width*.006);ctx.strokeRect(x,y,width,height);ctx.fillStyle="#0d2b20";ctx.fillRect(x,y,width,titleHeight);ctx.fillStyle="#f7fff4";ctx.font=`800 ${Math.max(16,width*.045)}px sans-serif`;ctx.textBaseline="middle";drawText(ctx,board.projectName||"工事件名",x+10,y+titleHeight/2,width-80,titleHeight*.8);ctx.fillStyle="#f1e08a";ctx.textAlign="right";ctx.fillText(`No.${board.photoNumber||"-"}`,x+width-10,y+titleHeight/2);ctx.textAlign="left";ctx.strokeStyle="rgba(239,247,231,.78)";ctx.lineWidth=Math.max(1,width*.0035);ctx.beginPath();ctx.moveTo(x,y+titleHeight);ctx.lineTo(x+width,y+titleHeight);ctx.moveTo(x+labelWidth,y+titleHeight);ctx.lineTo(x+labelWidth,y+height);let cy=y+titleHeight;rows.forEach((_,i)=>{cy+=(bodyHeight*weights[i])/total;ctx.moveTo(x,cy);ctx.lineTo(x+width,cy)});ctx.stroke();cy=y+titleHeight;rows.forEach(([label,value],i)=>{const rh=(bodyHeight*weights[i])/total,rowY=cy;cy+=rh;ctx.fillStyle="#eef7e9";ctx.font=`800 ${Math.max(12,width*.033)}px sans-serif`;ctx.textAlign="center";ctx.fillText(label,x+labelWidth/2,rowY+rh/2+1);ctx.textAlign="left";ctx.fillStyle="#fbfff7";ctx.font=`800 ${Math.max(13,width*.036)}px sans-serif`;drawText(ctx,value||"-",x+labelWidth+8,rowY+rh/2,width-labelWidth-16,rh*.86)});ctx.restore()}
function composePhoto(){readForm();const canvas=els.composeCanvas,ctx=canvas.getContext("2d"),width=state.photo?.naturalWidth||1280,height=state.photo?.naturalHeight||960;canvas.width=width;canvas.height=height;if(state.photo)ctx.drawImage(state.photo,0,0,width,height);else{ctx.fillStyle="#c6d0d9";ctx.fillRect(0,0,width,height);ctx.fillStyle="#51606f";ctx.font="700 42px sans-serif";ctx.textAlign="center";ctx.fillText("写真未選択",width/2,height/2);ctx.textAlign="left"}const scale=Number(els.boardScale.value)/100,bw=Math.round(width*scale),bh=Math.round(bw*.72),m=Math.round(width*.025),pos=els.boardPosition.value,x=pos.endsWith("right")?width-bw-m:m,y=pos.startsWith("top")?m:height-bh-m;drawBoardOnCanvas(ctx,x,y,bw,state.board);if(state.composedUrl)URL.revokeObjectURL(state.composedUrl);canvas.toBlob(blob=>{if(!blob)return;state.composedUrl=URL.createObjectURL(blob);els.downloadLink.href=state.composedUrl;els.downloadLink.download=makeImageName();els.downloadLink.setAttribute("aria-disabled","false")},"image/jpeg",.92)}
function makeImageName(){const p=(state.board.projectName||"project").replace(/[\\/:*?"<>|\s]+/g,"_");return`${p}_${state.board.photoNumber||"no"}_${state.board.workDate||"date"}.jpg`}
function csvCell(v){return`"${String(v??"").replaceAll('"','""')}"`}
function downloadText(filename,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)}
function exportJson(){downloadText("photo-book-records.json",JSON.stringify({version:1,exportedAt:new Date().toISOString(),photoBookRecords:state.history.map(r=>({photoNo:r.photoNumber,category:r.albumCategory,projectName:r.projectName,title:r.workType,location:r.location,shootingDate:r.workDate,photographer:r.worker,workContent:r.workContent,memo:r.note,createdAt:r.createdAt}))},null,2),"application/json")}
function exportCsv(){const headers=["写真番号","分類","工事件名","工種","場所","施工日","施工者","作業内容","備考","作成日時"],rows=state.history.map(r=>[r.photoNumber,r.albumCategory,r.projectName,r.workType,r.location,r.workDate,r.worker,r.workContent,r.note,r.createdAt]),csv=[headers,...rows].map(row=>row.map(csvCell).join(",")).join("\n");downloadText("photo-book-records.csv",`\uFEFF${csv}`,"text/csv;charset=utf-8")}
function bindEvents(){els.boardForm.addEventListener("input",()=>{readForm();enforceWorkContentLimit();renderBlackboard();persistState()});els.projectSelect.addEventListener("change",()=>{state.board.projectName=els.projectSelect.value;fillForm();renderAll();persistState()});els.saveProjectButton.addEventListener("click",()=>{readForm();if(state.board.projectName&&!state.projects.includes(state.board.projectName))state.projects.unshift(state.board.projectName);renderAll();persistState()});$$('.step-tabs button').forEach(b=>b.addEventListener("click",()=>setActivePanel(b.dataset.panel)));$$('[data-board-size]').forEach(b=>b.addEventListener("click",()=>{state.boardSize=b.dataset.boardSize;$$('[data-board-size]').forEach(x=>x.classList.toggle("active",x===b));renderBlackboard();persistState()}));$("#copyLastButton").addEventListener("click",()=>{if(state.history[0])copyFromRecord(state.history[0])});$("#duplicateButton").addEventListener("click",duplicateWithNextNumber);$("#newBoardButton").addEventListener("click",()=>{state.board=normalizeBoard({...defaultBoard,workDate:new Date().toISOString().slice(0,10)});fillForm();renderAll();persistState()});$("#saveButton").addEventListener("click",()=>saveCurrentBoard());$("#saveAndNextButton").addEventListener("click",()=>{saveCurrentBoard();duplicateWithNextNumber()});$("#composeButton").addEventListener("click",()=>{composePhoto();setActivePanel("photoPanel")});els.photoInput.addEventListener("change",e=>{const file=e.target.files?.[0];if(!file)return;const image=new Image();image.onload=()=>{state.photo=image;state.photoName=file.name;els.photoName.textContent=file.name;composePhoto()};image.src=URL.createObjectURL(file)});$("#clearPhotoButton").addEventListener("click",()=>{state.photo=null;state.photoName="";els.photoName.textContent="未選択";els.photoInput.value="";composePhoto()});els.boardPosition.addEventListener("change",composePhoto);els.boardScale.addEventListener("input",composePhoto);els.historyList.addEventListener("click",e=>{const b=e.target.closest("[data-copy-record]");if(!b)return;const r=state.history.find(x=>x.id===b.dataset.copyRecord);if(r)copyFromRecord(r)});$("#exportJsonButton").addEventListener("click",exportJson);$("#exportCsvButton").addEventListener("click",exportCsv);$("#clearHistoryButton").addEventListener("click",()=>{if(!confirm("履歴を削除しますか？"))return;state.history=[];renderHistory();persistState()})}
function registerServiceWorker(){if(!("serviceWorker" in navigator))return;navigator.serviceWorker.register("./sw.js").catch(()=>{})}
loadState();fillForm();bindEvents();renderAll();setActivePanel(state.selectedPanel||"inputPanel");composePhoto();registerServiceWorker();
